project:
  type: website
  output-dir: docs
  resources: 
    - google17429f0fe695a56c.html


website:
  title: "Annaly Aceves"
  navbar:
    left:

      - about.qmd
      - Photography.qmd
      - artwork.qmd
  page-footer: h
    
      
format: 
  html:
    css: 
      - styles.css



  
toc: true
lightbox: true


