project:
  type: website
  output-dir: docs
  resources: 
    - google17429f0fe695a56c.html


website:
  title: "Annaly Aceves"
  navbar:
    left:

      - about.qmd
     

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



