project:
  type: website
  output-dir: docs
  resources: 
    - google17429f0fe695a56c.html


website:
  title: "Annaly Aceves"
  navbar:
    left:

      - about.qmd
      - Photography.qmd
      - artwork.qmd
      
  page-footer:
    background: "#D7E2FA"
    left: 
      - icon: instagram
        href: https://www.instagram.com/annalys_fotos?igsh=MzRlODBiNWFlZA==
      - icon: github
        href: https://github.com/AnnalyAceves
    
      
format: 
  html:
    css: 
      - styles.css



  
toc: true
lightbox: true


